apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  dbname: {{ .Values.secret.dbname }}
  username: {{ .Values.secret.username }}
  password: {{ .Values.secret.password }}
